### ISSUE TITLE
Implementation for Issue/Task

### ISSUE THREAD

**Issue by gtakhar** [speng11/ProjectHub#5]
We want to have the ability to create issues/tasks. I don't know what we want to call these.

They should have the following fields.

- Title
- Description
- Created By
- Due Date
- Points
- Group (nullable)
- State (Open, In Progress, Finished?) Maybe even make this editable 
- Type (Bug, Feature, Enhancement)

This is just a starting point. If the issue/task is not assigned to group we should consider making it public. Or maybe we always want it to be associated with a group.

**Comment by speng11** [comment]
I was thinking that we might always want the issues/tasks to be associated with a group because it's up to each group to come up with their own tasks that are specific to their project. Also, maybe we can call the functionality "Create task" and when the user clicks on that button, a window/page will pop up and the user will be able to fill in those fields?
