### ISSUE TITLE
Group memberships

### ISSUE THREAD

**Issue by gtakhar** [speng11/ProjectHub#6]
I've already created a very basic group which only has a name at the moment.

We need to implement "Group Users" which will associate a relationship between the create and a user
GroupUser:
- id
- user_id
- group_id
- is_admin
- date_created

Then we want to enhance the group by possibly adding a description.

**Comment by raiyaj** [comment]
I just finished making the scaffold for this issue (still have to work on making an entry in the table when a user creates a group), but decided to call the table 'group_memberships' instead, because I think `has_many :group_memberships` makes more sense than `has_many :group_users` in the user model.

**Comment by raiyaj** [comment]
Next steps that I'll be working on for the first iteration: implementing a 'Group Requests' table, which will allow users to request to join groups and group admins to accept or deny these requests.
